import Head from "next/head";

export default function Home({ data }) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<table>
					<thead>
						<tr>
							<td> Name </td>
							<td> User name </td>
							<td> Email </td>
							<td> Phone </td>
							<td> Website </td>
						</tr>
					</thead>
					<tbody>
						{data.map((item) => (
							<tr key={item.id}>
								<td> {item.name} </td>
								<td> {item.username} </td>
								<td>{item.email} </td>
								<td> {item.phone}</td>
								<td> {item.website} </td>
							</tr>
						))}
					</tbody>
				</table>
			</main>
		</>
	);
}
export async function getStaticProps() {
	const res = await fetch("https://jsonplaceholder.typicode.com/users");
	const json = await res.json();
	return {
		props: { data: json },
	};
}
