import Head from "next/head";

export default function Home({ data }) {
	console.log(data);
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1>City: {data.name}</h1>
				<h2>Temp: {data.main.temp}</h2>
				<p>Weather: {data.weather[0].description}</p>
			</main>
		</>
	);
}
export async function getStaticProps() {
	const defaultApiConfig = {
		lat: 21.0245,
		lon: 105.8412,
		units: "metric",
		lang: "en",
		apiKey: "ee28afe45d0af688efc6e90041910bc3",
	};
	const createWetherRequest = (apiConfig) =>
		`https://api.openweathermap.org/data/2.5/weather?lat=${apiConfig.lat}&lon=${apiConfig.lon}&units=${apiConfig.units}&lang=${apiConfig.lang}&appid=${apiConfig.apiKey}`;

	const res = await fetch(createWetherRequest(defaultApiConfig));
	const json = await res.json();
	return {
		props: { data: json },
	};
}
